// Package manifest generates the two committed discoverability artifacts: the
// always-pinned agent manifest (the L0 keystone) and INDEX.md (the table of
// contents an agent reads before searching or opening files).
package manifest

import (
	"fmt"
	"os"
	"strings"

	"github.com/alxxpersonal/stardust/internal/index"
)

// WriteManifest writes the always-pinned agent manifest for a vault.
func WriteManifest(path, vaultName string) error {
	var b strings.Builder
	b.WriteString("# Stardust manifest\n\n")
	fmt.Fprintf(&b, "This is `%s`, a markdown vault indexed by Stardust.\n\n", vaultName)
	b.WriteString("## How to search it\n\n")
	b.WriteString("Run `stardust query \"<your question>\"` from anywhere in the vault. It returns\n")
	b.WriteString("the most relevant notes (hybrid keyword + semantic search) as markdown. Add\n")
	b.WriteString("`--output json` for structured results or `--limit N` to widen the result set.\n\n")
	b.WriteString("## What lives here\n\n")
	b.WriteString("See `.stardust/INDEX.md` for the table of contents. Files are the source of\n")
	b.WriteString("truth; the index is a derived cache rebuilt with `stardust index`.\n\n")
	b.WriteString("## Conventions\n\n")
	b.WriteString("- Notes are plain markdown with YAML frontmatter and `[[wikilinks]]`.\n")
	b.WriteString("- Search before answering. Do not assume a note does not exist without first\n")
	b.WriteString("  running `stardust query`.\n")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write manifest %s: %w", path, err)
	}
	return nil
}

// WriteIndex writes INDEX.md, a table of contents the agent reads first: title,
// path, and a one-line description per note.
func WriteIndex(path string, notes []index.NoteRow) error {
	var b strings.Builder
	b.WriteString("# Vault index\n\n")
	fmt.Fprintf(&b, "%d notes. Generated by `stardust index`. Read this first, then `stardust query` or open files directly.\n\n", len(notes))
	for _, n := range notes {
		title := n.Title
		if title == "" {
			title = n.Path
		}
		fmt.Fprintf(&b, "- **%s** - `%s`", title, n.Path)
		if n.Snippet != "" {
			b.WriteString("\n  " + oneLine(n.Snippet))
		}
		b.WriteString("\n")
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write index %s: %w", path, err)
	}
	return nil
}

func oneLine(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	if len(s) > 140 {
		s = strings.TrimSpace(s[:140]) + "..."
	}
	return s
}
