package manifest

import (
	"fmt"
	"os"
	"strings"
)

// RegistryRecord is one row in a docs registry group. Number is only used by the
// ADR group; the other groups leave it empty and render a Date column instead.
type RegistryRecord struct {
	Title  string
	Status string
	Path   string
	Date   string
	Number string
}

// RegistryGroup is a named collection of records, rendered as one section of the
// docs registry. The caller supplies groups in the order they should appear; the
// renderer never reorders them.
type RegistryGroup struct {
	Name    string
	Records []RegistryRecord
}

// AgentSkill is one skill row in the registry Agents section, listing a
// docs/agents-homed skill by name, description, and its sync targets.
type AgentSkill struct {
	Name        string
	Description string
	Targets     []string
}

// AgentSubagent is one subagent row in the registry Agents section, listing a
// docs/agents-homed subagent by name and description.
type AgentSubagent struct {
	Name        string
	Description string
}

// AgentsSection is the registry's agent-assets section: the shared skills and
// subagents homed under docs/agents. It renders after the doc collection groups
// so one glance at the registry shows the whole cross-agent surface.
type AgentsSection struct {
	Skills    []AgentSkill
	Subagents []AgentSubagent
}

// WriteRegistry renders the grouped docs registry and writes it to path,
// mirroring the WriteIndex write pattern.
func WriteRegistry(path string, groups []RegistryGroup, agents AgentsSection) error {
	if err := os.WriteFile(path, []byte(renderRegistry(groups, agents)), 0o644); err != nil {
		return fmt.Errorf("write registry %s: %w", path, err)
	}
	return nil
}

// renderRegistry builds the grouped markdown for the docs registry. Group order
// is preserved as given. The ADR group renders a numbered table; every other
// group renders a Title, Status, Doc, Date table. Empty groups render an
// empty-state line instead of a table. The Agents section follows the collection
// groups, listing the docs/agents-homed skills and subagents.
func renderRegistry(groups []RegistryGroup, agents AgentsSection) string {
	var b strings.Builder
	b.WriteString("# Docs Index\n\n")
	b.WriteString("Generated by `stardust registry`. Do not edit by hand.\n")
	for _, g := range groups {
		fmt.Fprintf(&b, "\n## %s\n\n", groupHeading(g.Name))
		if len(g.Records) == 0 {
			b.WriteString("No documents.\n")
			continue
		}
		if isADRGroup(g.Name) {
			b.WriteString("| # | Title | Status | Doc |\n")
			b.WriteString("|---|-------|--------|-----|\n")
			for _, r := range g.Records {
				fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", r.Number, r.Title, r.Status, r.Path)
			}
			continue
		}
		b.WriteString("| Title | Status | Doc | Date |\n")
		b.WriteString("|-------|--------|-----|------|\n")
		for _, r := range g.Records {
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", r.Title, r.Status, r.Path, r.Date)
		}
	}
	renderAgentsSection(&b, agents)
	return b.String()
}

// renderAgentsSection renders the docs/agents Agents section: a Skills table
// (name, description, targets) and a Subagents table (name, description). An
// empty area renders a single empty-state line, mirroring the collection groups.
func renderAgentsSection(b *strings.Builder, agents AgentsSection) {
	b.WriteString("\n## Agents\n\n")
	if len(agents.Skills) == 0 && len(agents.Subagents) == 0 {
		b.WriteString("No agent assets.\n")
		return
	}
	b.WriteString("### Skills\n\n")
	if len(agents.Skills) == 0 {
		b.WriteString("No skills.\n")
	} else {
		b.WriteString("| Name | Description | Targets |\n")
		b.WriteString("|------|-------------|---------|\n")
		for _, s := range agents.Skills {
			fmt.Fprintf(b, "| %s | %s | %s |\n", cellText(s.Name), cellText(s.Description), cellText(strings.Join(s.Targets, ", ")))
		}
	}
	b.WriteString("\n### Subagents\n\n")
	if len(agents.Subagents) == 0 {
		b.WriteString("No subagents.\n")
		return
	}
	b.WriteString("| Name | Description |\n")
	b.WriteString("|------|-------------|\n")
	for _, s := range agents.Subagents {
		fmt.Fprintf(b, "| %s | %s |\n", cellText(s.Name), cellText(s.Description))
	}
}

// cellText makes a value safe inside a markdown table cell: newlines collapse to
// spaces and pipes are escaped, so a long skill description never breaks a row.
func cellText(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", "\\|")
	return strings.TrimSpace(s)
}

// isADRGroup reports whether a group name denotes the ADR section, which uses a
// numbered table rather than a dated one.
func isADRGroup(name string) bool {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "adr", "adrs":
		return true
	default:
		return false
	}
}

// groupHeading maps a collection name to its registry section heading, matching
// the spec's fixed labels (Specs, Plans, ADRs, Research). Callers pass the raw
// collection name (the service uses lowercase slugs), so the heading is
// normalized here. An unknown name is capitalized so a custom collection still
// renders a reasonable heading.
func groupHeading(name string) string {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "specs":
		return "Specs"
	case "plans":
		return "Plans"
	case "adr", "adrs":
		return "ADRs"
	case "research":
		return "Research"
	default:
		n := strings.TrimSpace(name)
		if n == "" {
			return n
		}
		return strings.ToUpper(n[:1]) + n[1:]
	}
}
