package manifest

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestRenderRegistry(t *testing.T) {
	groups := []RegistryGroup{
		{
			Name: "Specs",
			Records: []RegistryRecord{
				{
					Title:  "Docs Convention and Versioning",
					Status: "Approved",
					Path:   "specs/2026-06-22-2238-docs-convention-and-versioning.md",
					Date:   "2026-06-22",
				},
			},
		},
		{Name: "Plans"},
	}

	out := renderRegistry(groups)

	require.Contains(t, out, "# Docs Index")
	require.Contains(t, out, "Generated by `stardust registry`. Do not edit by hand.")

	// Specs section with a populated table row.
	require.Contains(t, out, "## Specs")
	require.Contains(t, out, "| Title | Status | Doc | Date |")
	require.Contains(t, out, "| Docs Convention and Versioning | Approved | specs/2026-06-22-2238-docs-convention-and-versioning.md | 2026-06-22 |")

	// Plans section is present but empty, with an empty-state line.
	require.Contains(t, out, "## Plans")
	specsIdx := strings.Index(out, "## Specs")
	plansIdx := strings.Index(out, "## Plans")
	require.Less(t, specsIdx, plansIdx, "group order must be preserved")
	plansSection := out[plansIdx:]
	require.Contains(t, plansSection, "No documents.")
}

func TestRenderRegistryADRTable(t *testing.T) {
	groups := []RegistryGroup{
		{
			Name: "ADRs",
			Records: []RegistryRecord{
				{
					Number: "0001",
					Title:  "Adopt collections",
					Status: "Accepted",
					Path:   "adr/0001-adopt-collections.md",
				},
			},
		},
	}

	out := renderRegistry(groups)

	require.Contains(t, out, "## ADRs")
	require.Contains(t, out, "| # | Title | Status | Doc |")
	require.Contains(t, out, "| 0001 | Adopt collections | Accepted | adr/0001-adopt-collections.md |")
}

func TestRenderRegistryNormalizesHeadings(t *testing.T) {
	// The service passes lowercase collection slugs; headings must still render
	// as the spec's fixed labels (Specs, Plans, ADRs, Research).
	groups := []RegistryGroup{
		{Name: "specs"},
		{Name: "plans"},
		{Name: "adr"},
		{Name: "research"},
	}

	out := renderRegistry(groups)

	require.Contains(t, out, "## Specs")
	require.Contains(t, out, "## Plans")
	require.Contains(t, out, "## ADRs")
	require.Contains(t, out, "## Research")
	require.NotContains(t, out, "## specs")
	require.NotContains(t, out, "## adr\n")
}

func TestWriteRegistry(t *testing.T) {
	groups := []RegistryGroup{
		{
			Name: "Specs",
			Records: []RegistryRecord{
				{Title: "A spec", Status: "Draft", Path: "specs/a.md", Date: "2026-06-22"},
			},
		},
	}

	path := filepath.Join(t.TempDir(), "INDEX.md")
	require.NoError(t, WriteRegistry(path, groups))

	data, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, renderRegistry(groups), string(data))
}
