package manifest

import (
	"fmt"
	"os"
	"strings"
)

// RegistryRecord is one row in a docs registry group. Number is only used by the
// ADR group; the other groups leave it empty and render a Date column instead.
type RegistryRecord struct {
	Title  string
	Status string
	Path   string
	Date   string
	Number string
}

// RegistryGroup is a named collection of records, rendered as one section of the
// docs registry. The caller supplies groups in the order they should appear; the
// renderer never reorders them.
type RegistryGroup struct {
	Name    string
	Records []RegistryRecord
}

// WriteRegistry renders the grouped docs registry and writes it to path,
// mirroring the WriteIndex write pattern.
func WriteRegistry(path string, groups []RegistryGroup) error {
	if err := os.WriteFile(path, []byte(renderRegistry(groups)), 0o644); err != nil {
		return fmt.Errorf("write registry %s: %w", path, err)
	}
	return nil
}

// renderRegistry builds the grouped markdown for the docs registry. Group order
// is preserved as given. The ADR group renders a numbered table; every other
// group renders a Title, Status, Doc, Date table. Empty groups render an
// empty-state line instead of a table.
func renderRegistry(groups []RegistryGroup) string {
	var b strings.Builder
	b.WriteString("# Docs Index\n\n")
	b.WriteString("Generated by `stardust registry`. Do not edit by hand.\n")
	for _, g := range groups {
		fmt.Fprintf(&b, "\n## %s\n\n", g.Name)
		if len(g.Records) == 0 {
			b.WriteString("No documents.\n")
			continue
		}
		if isADRGroup(g.Name) {
			b.WriteString("| # | Title | Status | Doc |\n")
			b.WriteString("|---|-------|--------|-----|\n")
			for _, r := range g.Records {
				fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", r.Number, r.Title, r.Status, r.Path)
			}
			continue
		}
		b.WriteString("| Title | Status | Doc | Date |\n")
		b.WriteString("|-------|--------|-----|------|\n")
		for _, r := range g.Records {
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", r.Title, r.Status, r.Path, r.Date)
		}
	}
	return b.String()
}

// isADRGroup reports whether a group name denotes the ADR section, which uses a
// numbered table rather than a dated one.
func isADRGroup(name string) bool {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "adr", "adrs":
		return true
	default:
		return false
	}
}
